package Items;

public enum AdventuringGearEnum {
    abacus,
    animalTrophy,
    blanket,
    commonClothes,
    costume,
    crowbar,
    favorOfAnAdmirer,
    fineClothes,
    holySymbolAmulet,
    holySymbolEmblem,
    holySymbolReliquary,
    huntingTrap,
    ink,
    ironPot,
    letterOfIntroductionToGuild,
    prayerBook,
    markedCards,
    petMouse,
    quill,
    scrollCase,
    scrollOfPedigree,
    signetRing,
    shovel,
    silkRope,
    smallKnife,
    staff,
    stickOfEssence,
    stopperedBottle,
    travelersClothes,
    vestments,
    weightedDice
}
